name: Magic101Core
version: ${project.version}
main: net.dohaw.magic101core.Magic101Core
api-version: 1.17
commands:
  profile:
    description: Select a profile
  magic101:
    description: Base command for Magic101
    aliases: [mc]